vim.g.mapleader = " "
vim.cmd([[nmap <C-_> <Plug>NERDCommenterToggle]])
vim.cmd([[vmap <C-_> <Plug>NERDCommenterToggle<CR>gv]])
vim.cmd([[nmap <leader>p :Telescope sessions_picker<CR>]])
vim.cmd([[map <C-k> <C-w>k]])
vim.cmd([[map <C-j> <C-w>j]])
vim.cmd([[map <C-h> <C-w>h]])
vim.cmd([[map <C-l> <C-w>l]])
vim.cmd([[nmap <leader>D :bd!<CR>]])
vim.keymap.set("n", "<leader>e", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "gt", vim.cmd.bn)
vim.keymap.set("n", "gp", vim.cmd.bp)
vim.keymap.set("n", "<leader>d", vim.cmd.bd)
vim.keymap.set("n", "<leader>t", vim.cmd.ToggleTerm)
